-- This migration previously introduced team missions but was reordered.
-- It is intentionally left blank so the failed migration entry can be
-- marked as rolled back and re-applied without affecting the database.
