-- CreateEnum
CREATE TYPE "BattleMode" AS ENUM ('OFFICIAL_3ON3', 'REGIONAL_CIRCUIT', 'LONG_TRAINING', 'CUSTOM');

-- AlterTable
ALTER TABLE "Battle"
ADD COLUMN "mode" "BattleMode" NOT NULL DEFAULT 'OFFICIAL_3ON3';
